version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    environment:
      PGDATA: /var/lib/postgresql/data/transitspring_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transitspring_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: